name: Fetch Market Data
on:
  schedule:
    - cron: "*/10 * * * *"   # kas 10 min
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pyyaml
      - run: |
          python scripts/fetch.py
      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/quotes.json
          git commit -m "update data" || echo "No changes"
          git push
