name: Fetch Market Data
on:
  schedule:
    - cron: "*/10 * * * *"   # kas 10 min.
  workflow_dispatch:

permissions:
  contents: write   # leidžia github-actions[bot] commit'inti/push'inti

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pyyaml

      - name: Ensure data dir exists (saugiklis #1)
        run: mkdir -p data

      - name: Run fetcher
        run: python scripts/fetch.py

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/quotes.json
          git commit -m "update data" || echo "No changes"
          git push
