name: Fetch Market Data
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show HEAD (diagnostics)
        run: |
          echo "HEAD commit:" 
          git log -1 --oneline
          echo "CWD=$(pwd)"
          echo "Top tree:"
          ls -la
          echo "Show first lines of scripts/fetch.py"
          head -n 40 scripts/fetch.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pyyaml

      - name: Ensure data dir exists
        run: mkdir -p data

      - name: Run fetcher
        run: python scripts/fetch.py

      - name: Show output snippet
        run: |
          echo "quotes.json preview:"
          head -n 40 data/quotes.json || true

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/quotes.json
          git commit -m "update data" || echo "No changes"
          git push
